# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vagrant.plugins = ["vagrant-vbguest", "vagrant-disksize"]

  config.vm.box = "mwrock/Windows2016"
  config.vm.network "public_network"
  config.disksize.size = "40000MB"

  config.vm.provider "virtualbox" do |vb|

    vb.gui = true
    vb.memory = "8000"
  end
end
